version: '3'

services:
   oracledb:
     image: wnameless/oracle-xe-11g
     ports:
      - "1521:1521"

   php7-with-oci8:
     depends_on:
       - oracledb
     image: adrianharabula/php7-with-oci8
     volumes:
      - ./www:/var/www/html
     ports:
      - "8181:80"

